
package com.lic.insurance.bff.model.policy;
import java.io.Serializable;
import java.math.BigDecimal;
/**
 * This class was automatically generated by the data modeler tool.
 */
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class SpotRevivalRq implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SpotRevivalRq() {
    }
    
    private BigDecimal policyNumber;
	private String commencement;
	private String dateOfCalc;
	private String dateOfBirth;
	private String dateOfBirth2ndlife;
	private Integer planNum;
	private BigDecimal instPremium;
	private Integer sumAssured;
	private Integer fup;
	private Integer pmo02Mode;
	private Integer policyTerm;
	private Integer payingTerm;
	private Integer accumTerm;
	private Integer policyStatus;
	private String serbranch;
	private String altChnlId;
	private String ageProofCode;
	private String nextPremChange;
	private String lastPremChange;
	private String stsChangeDate;
	private Integer pmGaps;
	private String pmInstRevFlag;
	private Integer pmCampaignRevival;
	private String medicalcode;
	private String extraspresent;
	private String riderspresent;
	private String nriFlag;
	private String countryCode;
	private Integer chartCode;
	private BigDecimal CDACharges;
	
	private String fromDue;
	private String uptoDue;
	private Integer noofDues;
	private BigDecimal totalPremium;
	private BigDecimal netLateFee;
	private BigDecimal gSTonPremium;
	private BigDecimal gSTonLateFee;
	private BigDecimal gSTonCDACharges;
	
	private Boolean isSpotRevivalAllowed;

	/**
	 * @return the fromDue
	 */
	public String getFromDue() {
		return fromDue;
	}
	/**
	 * @param fromDue the fromDue to set
	 */
	public void setFromDue(String fromDue) {
		this.fromDue = fromDue;
	}
	/**
	 * @return the uptoDue
	 */
	public String getUptoDue() {
		return uptoDue;
	}
	/**
	 * @param uptoDue the uptoDue to set
	 */
	public void setUptoDue(String uptoDue) {
		this.uptoDue = uptoDue;
	}
	/**
	 * @return the noofDues
	 */
	public Integer getNoofDues() {
		return noofDues;
	}
	/**
	 * @param noofDues the noofDues to set
	 */
	public void setNoofDues(Integer noofDues) {
		this.noofDues = noofDues;
	}
	/**
	 * @return the totalPremium
	 */
	public BigDecimal getTotalPremium() {
		return totalPremium;
	}
	/**
	 * @param totalPremium the totalPremium to set
	 */
	public void setTotalPremium(BigDecimal totalPremium) {
		this.totalPremium = totalPremium;
	}
	/**
	 * @return the netLateFee
	 */
	public BigDecimal getNetLateFee() {
		return netLateFee;
	}
	/**
	 * @param netLateFee the netLateFee to set
	 */
	public void setNetLateFee(BigDecimal netLateFee) {
		this.netLateFee = netLateFee;
	}
	/**
	 * @return the gSTonPremium
	 */
	public BigDecimal getgSTonPremium() {
		return gSTonPremium;
	}
	/**
	 * @param gSTonPremium the gSTonPremium to set
	 */
	public void setgSTonPremium(BigDecimal gSTonPremium) {
		this.gSTonPremium = gSTonPremium;
	}
	/**
	 * @return the gSTonLateFee
	 */
	public BigDecimal getgSTonLateFee() {
		return gSTonLateFee;
	}
	/**
	 * @param gSTonLateFee the gSTonLateFee to set
	 */
	public void setgSTonLateFee(BigDecimal gSTonLateFee) {
		this.gSTonLateFee = gSTonLateFee;
	}
	/**
	 * @return the gSTonCDACharges
	 */
	public BigDecimal getgSTonCDACharges() {
		return gSTonCDACharges;
	}
	/**
	 * @param gSTonCDACharges the gSTonCDACharges to set
	 */
	public void setgSTonCDACharges(BigDecimal gSTonCDACharges) {
		this.gSTonCDACharges = gSTonCDACharges;
	}
	/**
	 * @return the commencement
	 */
	public String getCommencement() {
		return commencement;
	}
	/**
	 * @param commencement the commencement to set
	 */
	public void setCommencement(String commencement) {
		this.commencement = commencement;
	}
	/**
	 * @return the dateOfCalc
	 */
	public String getDateOfCalc() {
		return dateOfCalc;
	}
	/**
	 * @param dateOfCalc the dateOfCalc to set
	 */
	public void setDateOfCalc(String dateOfCalc) {
		this.dateOfCalc = dateOfCalc;
	}
	/**
	 * @return the dateOfBirth
	 */
	public String getDateOfBirth() {
		return dateOfBirth;
	}
	/**
	 * @param dateOfBirth the dateOfBirth to set
	 */
	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}
	/**
	 * @return the dateOfBirth2ndlife
	 */
	public String getDateOfBirth2ndlife() {
		return dateOfBirth2ndlife;
	}
	/**
	 * @param dateOfBirth2ndlife the dateOfBirth2ndlife to set
	 */
	public void setDateOfBirth2ndlife(String dateOfBirth2ndlife) {
		this.dateOfBirth2ndlife = dateOfBirth2ndlife;
	}
	/**
	 * @return the planNum
	 */
	public Integer getPlanNum() {
		return planNum;
	}
	/**
	 * @param planNum the planNum to set
	 */
	public void setPlanNum(Integer planNum) {
		this.planNum = planNum;
	}
	/**
	 * @return the instPremium
	 */
	public BigDecimal getInstPremium() {
		return instPremium;
	}
	/**
	 * @param instPremium the instPremium to set
	 */
	public void setInstPremium(BigDecimal instPremium) {
		this.instPremium = instPremium;
	}
	/**
	 * @return the sumAssured
	 */
	public Integer getSumAssured() {
		return sumAssured;
	}
	/**
	 * @param sumAssured the sumAssured to set
	 */
	public void setSumAssured(Integer sumAssured) {
		this.sumAssured = sumAssured;
	}
	/**
	 * @return the fup
	 */
	public Integer getFup() {
		return fup;
	}
	/**
	 * @param fup the fup to set
	 */
	public void setFup(Integer fup) {
		this.fup = fup;
	}
	/**
	 * @return the pmo02Mode
	 */
	public Integer getPmo02Mode() {
		return pmo02Mode;
	}
	/**
	 * @param pmo02Mode the pmo02Mode to set
	 */
	public void setPmo02Mode(Integer pmo02Mode) {
		this.pmo02Mode = pmo02Mode;
	}
	/**
	 * @return the policyTerm
	 */
	public Integer getPolicyTerm() {
		return policyTerm;
	}
	/**
	 * @param policyTerm the policyTerm to set
	 */
	public void setPolicyTerm(Integer policyTerm) {
		this.policyTerm = policyTerm;
	}
	/**
	 * @return the payingTerm
	 */
	public Integer getPayingTerm() {
		return payingTerm;
	}
	/**
	 * @param payingTerm the payingTerm to set
	 */
	public void setPayingTerm(Integer payingTerm) {
		this.payingTerm = payingTerm;
	}
	/**
	 * @return the accumTerm
	 */
	public Integer getAccumTerm() {
		return accumTerm;
	}
	/**
	 * @param accumTerm the accumTerm to set
	 */
	public void setAccumTerm(Integer accumTerm) {
		this.accumTerm = accumTerm;
	}
	/**
	 * @return the policyStatus
	 */
	public Integer getPolicyStatus() {
		return policyStatus;
	}
	/**
	 * @param policyStatus the policyStatus to set
	 */
	public void setPolicyStatus(Integer policyStatus) {
		this.policyStatus = policyStatus;
	}
	/**
	 * @return the serbranch
	 */
	public String getSerbranch() {
		return serbranch;
	}
	/**
	 * @param serbranch the serbranch to set
	 */
	public void setSerbranch(String serbranch) {
		this.serbranch = serbranch;
	}
	/**
	 * @return the altChnlId
	 */
	public String getAltChnlId() {
		return altChnlId;
	}
	/**
	 * @param altChnlId the altChnlId to set
	 */
	public void setAltChnlId(String altChnlId) {
		this.altChnlId = altChnlId;
	}
	/**
	 * @return the ageProofCode
	 */
	public String getAgeProofCode() {
		return ageProofCode;
	}
	/**
	 * @param ageProofCode the ageProofCode to set
	 */
	public void setAgeProofCode(String ageProofCode) {
		this.ageProofCode = ageProofCode;
	}
	/**
	 * @return the nextPremChange
	 */
	public String getNextPremChange() {
		return nextPremChange;
	}
	/**
	 * @param nextPremChange the nextPremChange to set
	 */
	public void setNextPremChange(String nextPremChange) {
		this.nextPremChange = nextPremChange;
	}
	/**
	 * @return the lastPremChange
	 */
	public String getLastPremChange() {
		return lastPremChange;
	}
	/**
	 * @param lastPremChange the lastPremChange to set
	 */
	public void setLastPremChange(String lastPremChange) {
		this.lastPremChange = lastPremChange;
	}
	/**
	 * @return the stsChangeDate
	 */
	public String getStsChangeDate() {
		return stsChangeDate;
	}
	/**
	 * @param stsChangeDate the stsChangeDate to set
	 */
	public void setStsChangeDate(String stsChangeDate) {
		this.stsChangeDate = stsChangeDate;
	}
	/**
	 * @return the pmGaps
	 */
	public Integer getPmGaps() {
		return pmGaps;
	}
	/**
	 * @param pmGaps the pmGaps to set
	 */
	public void setPmGaps(Integer pmGaps) {
		this.pmGaps = pmGaps;
	}
/**
	 * @return the pmInstRevFlag
	 */
	public String getPmInstRevFlag() {
		return pmInstRevFlag;
	}
	/**
	 * @param pmInstRevFlag the pmInstRevFlag to set
	 */
	public void setPmInstRevFlag(String pmInstRevFlag) {
		this.pmInstRevFlag = pmInstRevFlag;
	}
	
	/**
	 * @return the pmCampaignRevival
	 */
	public Integer getPmCampaignRevival() {
		return pmCampaignRevival;
	}
	/**
	 * @param pmCampaignRevival the pmCampaignRevival to set
	 */
	public void setPmCampaignRevival(Integer pmCampaignRevival) {
		this.pmCampaignRevival = pmCampaignRevival;
	}
	/**
	 * @return the medicalcode
	 */
	public String getMedicalcode() {
		return medicalcode;
	}
	/**
	 * @param medicalcode the medicalcode to set
	 */
	public void setMedicalcode(String medicalcode) {
		this.medicalcode = medicalcode;
	}
	/**
	 * @return the extraspresent
	 */
	public String getExtraspresent() {
		return extraspresent;
	}
	/**
	 * @param extraspresent the extraspresent to set
	 */
	public void setExtraspresent(String extraspresent) {
		this.extraspresent = extraspresent;
	}
	/**
	 * @return the riderspresent
	 */
	public String getRiderspresent() {
		return riderspresent;
	}
	/**
	 * @param riderspresent the riderspresent to set
	 */
	public void setRiderspresent(String riderspresent) {
		this.riderspresent = riderspresent;
	}
	/**
	 * @return the nriFlag
	 */
	public String getNriFlag() {
		return nriFlag;
	}
	/**
	 * @param nriFlag the nriFlag to set
	 */
	public void setNriFlag(String nriFlag) {
		this.nriFlag = nriFlag;
	}
	/**
	 * @return the countryCode
	 */
	public String getCountryCode() {
		return countryCode;
	}
	/**
	 * @param countryCode the countryCode to set
	 */
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}
	/**
	 * @return the chartCode
	 */
	public Integer getChartCode() {
		return chartCode;
	}
	/**
	 * @param chartCode the chartCode to set
	 */
	public void setChartCode(Integer chartCode) {
		this.chartCode = chartCode;
	}
	/**
	 * @return the cDACharges
	 */
	public BigDecimal getCDACharges() {
		return CDACharges;
	}
	/**
	 * @param cDACharges the cDACharges to set
	 */
	public void setCDACharges(BigDecimal cDACharges) {
		CDACharges = cDACharges;
	}
	/**
	 * @return the policyNumber
	 */
	public BigDecimal getPolicyNumber() {
		return policyNumber;
	}
	/**
	 * @param policyNumber the policyNumber to set
	 */
	public void setPolicyNumber(BigDecimal policyNumber) {
		this.policyNumber = policyNumber;
	}
	
	public Boolean getIsSpotRevivalAllowed() {
		return isSpotRevivalAllowed;
	}
	/**
	 * @param isSpotRevivalAllowed the isSpotRevivalAllowed to set
	 */
	public void setIsSpotRevivalAllowed(Boolean isSpotRevivalAllowed) {
		this.isSpotRevivalAllowed = isSpotRevivalAllowed;
	}
	

}